"""CLI: convert CSV sample logs into Sigma rules."""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

from sigma_converter import CsvToSigmaConverter
from sigma_converter.converter import DetectionRule


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="CSV → Sigma rule converter")
    p.add_argument("csv", type=Path, help="Path to CSV file with log records")
    p.add_argument("title", help="Sigma rule title")
    p.add_argument("--id", default=None, help="Sigma rule id (auto-generated if omitted)")
    p.add_argument("--out", type=Path, default=None, help="Output file (default stdout)")
    p.add_argument("--level", default="medium", help="Rule severity level")
    p.add_argument("--timeframe", default="5m", help="Condition timeframe")
    return p.parse_args()


def build_rule(title: str, rule_id: str | None, level: str, timeframe: str) -> DetectionRule:
    return DetectionRule(
        title=title,
        id=rule_id or title.lower().replace(" ", "-")[:32],
        description="Auto-generated by soc-automation sigma_converter",
        author="soc-automation",
        date="2026-06-23",
        level=level,
    )


def main(argv: list[str] | None = None) -> int:
    args = parse_args()
    csv_data = Path(args.csv).read_text(encoding="utf-8")
    converter = CsvToSigmaConverter()
    rule = build_rule(args.title, args.id, args.level, args.timeframe)

    rendered = converter.convert(csv_data, rule)

    if args.out:
        args.out.write_text(rendered + "\n", encoding="utf-8")
    else:
        sys.stdout.write(rendered + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
