"""CLI: convert CSV/JSONL logs into Sigma rules from the terminal."""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

from sigma_converter import CsvToSigmaConverter, DetectionRule, FieldMapping


PARSERS = {
    "csv": "Convert CSV-formatted logs",
    "jsonl": "Convert JSON Lines (.jsonl) logs",
}


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Convert application logs into Sigma detection rules.",
        epilog="Example: sigma-conv access.log.csv 'HTTP Admin Access' --format csv",
    )
    p.add_argument("input", type=Path, help="Path to log file (.csv or .jsonl)")
    p.add_argument("title", help="Sigma rule title")
    p.add_argument(
        "--format",
        choices=PARSERS,
        default="csv",
        help="Input log format (default: csv)",
    )
    p.add_argument("--id", default=None, help="Sigma rule id (auto-generated if omitted)")
    p.add_argument(
        "--out", type=Path, default=None, help="Output file (default: stdout)"
    )
    p.add_argument("--level", default="medium", help="Rule severity level")
    p.add_argument(
        "--mapping",
        action="append",
        default=None,
        help="Field mapping in source:sigma_field:transform form, repeatable",
    )
    return p.parse_args()


def _parse_mappings(raw_mappings: list[str] | None) -> list[FieldMapping] | None:
    if not raw_mappings:
        return None
    mappings: list[FieldMapping] = []
    for item in raw_mappings:
        parts = item.split(":")
        if len(parts) < 2:
            raise ValueError(f"Invalid mapping: {item}")
        source = parts[0]
        sigma_field = parts[1]
        transform = parts[2] if len(parts) > 2 else "raw"
        mappings.append(FieldMapping(source=source, sigma_field=sigma_field, transform=transform))
    return mappings


def build_rule(title: str, rule_id: str | None, level: str) -> DetectionRule:
    from datetime import date

    return DetectionRule(
        title=title,
        id=rule_id or title.lower().replace(" ", "-")[:32],
        description="Auto-generated by soc-automation sigma_converter",
        author="soc-automation",
        date=date.today().isoformat(),
        level=level,
    )


def main(argv: list[str] | None = None) -> int:
    args = parse_args()
    if not args.input.exists():
        raise SystemExit(f"Input file not found: {args.input}")

    data = args.input.read_text(encoding="utf-8")
    mappings = _parse_mappings(args.mapping)
    rule = build_rule(args.title, args.id, args.level)

    converter = CsvToSigmaConverter(mappings=mappings)
    rendered = converter.convert_csv(data, rule) if args.format == "csv" else converter.convert_jsonl(data, rule)

    if args.out:
        args.out.write_text(rendered + "\n", encoding="utf-8")
        print(f"Sigma rule written to {args.out}")
    else:
        sys.stdout.write(rendered + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
